apiVersion: v1
kind: Service
metadata:
  name: odoo-postgres-service-init
spec:
  selector:
    app: odoo-postgres-init
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-service-init
spec:
  selector:
    app: odoo-init
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
      nodePort: 30010
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: odoo-postgres-pod-init
  labels:
    app: odoo-postgres-init
spec:
  containers:
    - name: postgres-init
      image: postgres:15
      env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: odoo
        - name: POSTGRES_DB
          value: odoo
        - name: PGDATA
          value: /var/lib/postgresql/data
      volumeMounts:
        - name: postgres-data-volume
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-data-volume
      hostPath:
        path: /home/master/volume/pre-production/postgres
---
apiVersion: v1
kind: Pod
metadata:
  name: odoo-pod-init
  labels:
    app: odoo-init
spec:
  containers:
    - name: odoo-init
      image: odoo:16
      command: ["/bin/sh", "-c"]
      args:
        - odoo --init base --db_host $HOST --db_port $PORT --db_user $USER --db_password $PASSWORD --database odoo --dev all
      ports:
        - containerPort: 8069
      env:
        - name: HOST
          value: odoo-postgres-service-init
        - name: PORT
          value: "5432"
        - name: USER
          value: odoo
        - name: PASSWORD
          value: odoo
