apiVersion: v1
kind: Service
metadata:
  name: odoo-postgres-service-prepod
spec:
  selector:
    app: odoo-postgres-prepod
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-service-prepod
spec:
  selector:
    app: odoo-prepod
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
      nodePort: 30010
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: odoo-postgres-pod-prepod
  labels:
    app: odoo-postgres-prepod
spec:
  containers:
    - name: postgres-prepod
      image: postgres:15
      env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: odoo
        - name: PGDATA
          value: /var/lib/postgresql/data
      volumeMounts:
        - name: postgres-data-volume
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-data-volume
      hostPath:
        path: /home/master/volume/pre-production/postgres
---
apiVersion: v1
kind: Pod
metadata:
  name: odoo-pod-prepod
  labels:
    app: odoo-prepod
spec:
  containers:
    - name: odoo-prepod
      image: odoo:16
      ports:
        - containerPort: 8069
      env:
        - name: HOST
          value: odoo-postgres-service-prepod
        - name: PORT
          value: "5432"
        - name: USER
          value: odoo
        - name: PASSWORD
          value: odoo
