apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config-preprod
data:
  odoo.conf: |
    [options]
    admin_user = admin@example.com
    admin_passwd = admin
    db_host = odoo-postgres-service-preprod
    db_port = 5432
    db_user = odoo
    db_password = odoo
    addons_path = /mnt/extra-addons
    debug_mode = True
    test_enable = True
    test_all = True
    [database]
    db_name = odoo
    db_filter = odoo_*
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-preprod
data:
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 100
    shared_buffers = 128MB
    effective_cache_size = 512MB
    work_mem = 4MB
    maintenance_work_mem = 64MB
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-postgres-service-preprod
spec:
  selector:
    app: odoo-postgres-preprod
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-service-preprod
spec:
  selector:
    app: odoo-preprod
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
      nodePort: 30010
  type: NodePort
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-data
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  storageClassName: storageclass-odoo
  local:
    path: /home/master/volume/pre-production/postgres/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - k8s-master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: storageclass-odoo
  volumeName: postgres-pv-data
---
apiVersion: v1
kind: Pod
metadata:
  name: odoo-postgres-pod-preprod
  labels:
    app: odoo-postgres-preprod
spec:
  containers:
    - name: postgres-preprod
      image: postgres:15
      env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: odoo
        - name: POSTGRES_DB
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      volumeMounts:
        - name: postgres-data-volume
          mountPath: /var/lib/postgresql/data/pgdata
  volumes:
    - name: postgres-data-volume
      persistentVolumeClaim:
        claimName: postgres-pvc-data
---
apiVersion: v1
kind: Pod
metadata:
  name: odoo-pod-preprod
  labels:
    app: odoo-preprod
spec:
  initContainers:
    - name: wait-for-postgres
      image: bitnami/kubectl:1.27.7-debian-11-r0
      command: ["sh", "-c", "until kubectl --namespace pre-production get pod odoo-postgres-pod-prepod -o jsonpath='{.status.phase}' | grep -q Running; do sleep 1; done"]
  containers:
    - name: odoo-preprod
      image: odoo:16
      ports:
        - containerPort: 8069
      env:
        - name: HOST
          value: odoo-postgres-service-preprod
        - name: PORT
          value: "5432"
        - name: USER
          value: odoo
        - name: PASSWORD
          value: odoo
        - name: DATABASE
          value: odoo
      volumeMounts:
        - name: config-volume
          mountPath: /etc/odoo/odoo.conf
          subPath: odoo.conf
        - name: addons-volume
          mountPath: /mnt/extra-addons
  volumes:
    - name: config-volume
      configMap:
        name: odoo-config-preprod
    - name: addons-volume
      hostPath:
        path: /home/master/volume/pre-production/odoo/addons
