apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-build
data:
  postgres.conf: |
    listen_addresses = '*'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config-build
data:
  odoo.conf: |
    [options]
    admin_user = admin@example.com
    admin_passwd = admin
    addons_path = /mnt/extra-addons
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-postgres-service-build
spec:
  selector:
    app: odoo-postgres-build
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-service-build
spec:
  selector:
    app: odoo-build
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: odoo-postgres-pod-build
  labels:
    app: odoo-postgres-build
spec:
  containers:
    - name: postgres-build
      image: postgres:15
      env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: odoo
      volumeMounts:
        - name: postgres-config-volume
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
  volumes:
    - name: postgres-config-volume
      configMap:
        name: postgres-config-build
---
apiVersion: v1
kind: Pod
metadata:
  name: odoo-pod-build
  labels:
    app: odoo-build
spec:
  containers:
    - name: odoo-build
      image: odoo:16
      ports:
        - containerPort: 8069
      env:
        - name: HOST
          value: odoo-postgres-service-build
        - name: PORT
          value: "5432"
        - name: USER
          value: odoo
        - name: PASSWORD
          value: odoo
      volumeMounts:
        - name: config-volume
          mountPath: /etc/odoo/odoo.conf
          subPath: odoo.conf
  volumes:
    - name: config-volume
      configMap:
        name: odoo-config-build
